[env:due]
platform = atmelsam
board = due
framework = arduino

monitor_speed = 115200
;skip verify
upload_flags = -v 

debug_tool = blackmagic
debug_port = \\.\COM4 ; Replace with your FIRST Black Magic COM port

; Point PlatformIO to your local ARM toolchain
platform_packages =
    toolchain-gccarmnoneeabi @ symlink://C:/armtoolchain

build_unflags = 
    -std=gnu++11
    -fexceptions
    ;-Og


build_flags = 
    -std=gnu++23
    -O3
    -Wno-register
    -Wno-volatile
    -Wno-unused-variable
    -Wno-narrowing
    -fno-exceptions
    -Wl,--no-warn-rwx-segments ; Silences the RWX warning


; Force debug mode to use O3 but append GDB symbols
debug_build_flags = 
    -Og
    -g2
    -ggdb2

debug_load_cmds = preload

lib_deps = 
    symlink://C:/arduinolibs/SAM3XDUE
