#pragma once
#include <SAM3XDUE.H>

#ifndef DUE_DOOM_TEXTURES
#define DUE_DOOM_TEXTURES

constexpr uint16_t C_YEL = 0xFFE0; // Yellow
constexpr uint16_t C_BLK = 0x2104; // Dark Grey
constexpr uint16_t C_RED = 0xF800; // Red
constexpr uint16_t C_DRD = 0x8000; // Dark Red

// Type 1: Red Brick Pattern
extern const uint16_t tex_type1[256] = {
    C_RED, C_RED, C_RED, C_RED, C_RED, C_RED, C_RED, C_RED, C_RED, C_RED, C_RED, C_RED, C_RED, C_RED, C_RED, C_DRD,
    C_RED, C_RED, C_RED, C_RED, C_RED, C_RED, C_RED, C_RED, C_RED, C_RED, C_RED, C_RED, C_RED, C_RED, C_RED, C_DRD,
    C_RED, C_RED, C_RED, C_RED, C_RED, C_RED, C_RED, C_RED, C_RED, C_RED, C_RED, C_RED, C_RED, C_RED, C_RED, C_DRD,
    C_DRD, C_DRD, C_DRD, C_DRD, C_DRD, C_DRD, C_DRD, C_DRD, C_DRD, C_DRD, C_DRD, C_DRD, C_DRD, C_DRD, C_DRD, C_DRD,
    C_RED, C_RED, C_RED, C_RED, C_RED, C_RED, C_RED, C_DRD, C_RED, C_RED, C_RED, C_RED, C_RED, C_RED, C_RED, C_DRD,
    C_RED, C_RED, C_RED, C_RED, C_RED, C_RED, C_RED, C_DRD, C_RED, C_RED, C_RED, C_RED, C_RED, C_RED, C_RED, C_DRD,
    C_RED, C_RED, C_RED, C_RED, C_RED, C_RED, C_RED, C_DRD, C_RED, C_RED, C_RED, C_RED, C_RED, C_RED, C_RED, C_DRD,
    C_DRD, C_DRD, C_DRD, C_DRD, C_DRD, C_DRD, C_DRD, C_DRD, C_DRD, C_DRD, C_DRD, C_DRD, C_DRD, C_DRD, C_DRD, C_DRD,
    C_RED, C_RED, C_RED, C_RED, C_RED, C_RED, C_RED, C_RED, C_RED, C_RED, C_RED, C_RED, C_RED, C_RED, C_RED, C_DRD,
    C_RED, C_RED, C_RED, C_RED, C_RED, C_RED, C_RED, C_RED, C_RED, C_RED, C_RED, C_RED, C_RED, C_RED, C_RED, C_DRD,
    C_RED, C_RED, C_RED, C_RED, C_RED, C_RED, C_RED, C_RED, C_RED, C_RED, C_RED, C_RED, C_RED, C_RED, C_RED, C_DRD,
    C_DRD, C_DRD, C_DRD, C_DRD, C_DRD, C_DRD, C_DRD, C_DRD, C_DRD, C_DRD, C_DRD, C_DRD, C_DRD, C_DRD, C_DRD, C_DRD,
    C_RED, C_RED, C_RED, C_DRD, C_RED, C_RED, C_RED, C_RED, C_RED, C_RED, C_RED, C_DRD, C_RED, C_RED, C_RED, C_RED,
    C_RED, C_RED, C_RED, C_DRD, C_RED, C_RED, C_RED, C_RED, C_RED, C_RED, C_RED, C_DRD, C_RED, C_RED, C_RED, C_RED,
    C_RED, C_RED, C_RED, C_DRD, C_RED, C_RED, C_RED, C_RED, C_RED, C_RED, C_RED, C_DRD, C_RED, C_RED, C_RED, C_RED,
    C_DRD, C_DRD, C_DRD, C_DRD, C_DRD, C_DRD, C_DRD, C_DRD, C_DRD, C_DRD, C_DRD, C_DRD, C_DRD, C_DRD, C_DRD, C_DRD
};

// Type 2: Caution Stripe
extern const uint16_t tex_type2[256] = {
    C_YEL,C_YEL,C_YEL,C_YEL, C_BLK,C_BLK,C_BLK,C_BLK, C_YEL,C_YEL,C_YEL,C_YEL, C_BLK,C_BLK,C_BLK,C_BLK,
    C_YEL,C_YEL,C_YEL,C_YEL, C_YEL,C_BLK,C_BLK,C_BLK, C_BLK,C_YEL,C_YEL,C_YEL, C_YEL,C_BLK,C_BLK,C_BLK,
    C_BLK,C_YEL,C_YEL,C_YEL, C_YEL,C_YEL,C_BLK,C_BLK, C_BLK,C_BLK,C_YEL,C_YEL, C_YEL,C_YEL,C_BLK,C_BLK,
    C_BLK,C_BLK,C_YEL,C_YEL, C_YEL,C_YEL,C_YEL,C_BLK, C_BLK,C_BLK,C_BLK,C_YEL, C_YEL,C_YEL,C_YEL,C_BLK,
    C_BLK,C_BLK,C_BLK,C_YEL, C_YEL,C_YEL,C_YEL,C_YEL, C_BLK,C_BLK,C_BLK,C_BLK, C_YEL,C_YEL,C_YEL,C_YEL,
    C_YEL,C_BLK,C_BLK,C_BLK, C_BLK,C_YEL,C_YEL,C_YEL, C_YEL,C_BLK,C_BLK,C_BLK, C_BLK,C_YEL,C_YEL,C_YEL,
    C_YEL,C_YEL,C_BLK,C_BLK, C_BLK,C_BLK,C_YEL,C_YEL, C_YEL,C_YEL,C_BLK,C_BLK, C_BLK,C_BLK,C_YEL,C_YEL,
    C_YEL,C_YEL,C_YEL,C_BLK, C_BLK,C_BLK,C_BLK,C_YEL, C_YEL,C_YEL,C_YEL,C_BLK, C_BLK,C_BLK,C_BLK,C_YEL,
    C_YEL,C_YEL,C_YEL,C_YEL, C_BLK,C_BLK,C_BLK,C_BLK, C_YEL,C_YEL,C_YEL,C_YEL, C_BLK,C_BLK,C_BLK,C_BLK,
    C_YEL,C_YEL,C_YEL,C_YEL, C_YEL,C_BLK,C_BLK,C_BLK, C_BLK,C_YEL,C_YEL,C_YEL, C_YEL,C_BLK,C_BLK,C_BLK,
    C_BLK,C_YEL,C_YEL,C_YEL, C_YEL,C_YEL,C_BLK,C_BLK, C_BLK,C_BLK,C_YEL,C_YEL, C_YEL,C_YEL,C_BLK,C_BLK,
    C_BLK,C_BLK,C_YEL,C_YEL, C_YEL,C_YEL,C_YEL,C_BLK, C_BLK,C_BLK,C_BLK,C_YEL, C_YEL,C_YEL,C_YEL,C_BLK,
    C_BLK,C_BLK,C_BLK,C_YEL, C_YEL,C_YEL,C_YEL,C_YEL, C_BLK,C_BLK,C_BLK,C_BLK, C_YEL,C_YEL,C_YEL,C_YEL,
    C_YEL,C_BLK,C_BLK,C_BLK, C_BLK,C_YEL,C_YEL,C_YEL, C_YEL,C_BLK,C_BLK,C_BLK, C_BLK,C_YEL,C_YEL,C_YEL,
    C_YEL,C_YEL,C_BLK,C_BLK, C_BLK,C_BLK,C_YEL,C_YEL, C_YEL,C_YEL,C_BLK,C_BLK, C_BLK,C_BLK,C_YEL,C_YEL,
    C_YEL,C_YEL,C_YEL,C_BLK, C_BLK,C_BLK,C_BLK,C_YEL, C_YEL,C_YEL,C_YEL,C_BLK, C_BLK,C_BLK,C_BLK,C_YEL
};

// Global lookup table (Index 0 is null to handle empty map spaces safely)
extern const uint16_t* const wall_textures[] = {
    nullptr,
    tex_type1,
    tex_type2
};

#endif